name: Build and Push Docker Image

on:
  release:
    types: [published]
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for preview
        id: meta-preview
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/sendlix-smtp-relay
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=preview-,format=short

      - name: Build and push preview image
        uses: docker/build-push-action@v4
        with:
          context: ./Sendlix.Smpt.Relay
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta-preview.outputs.tags }}
          labels: ${{ steps.meta-preview.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/sendlix-smtp-relay
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=tag
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Sendlix.Smpt.Relay
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
